name: SwiftPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: .build
        key: build-${{ github.workspace }}-${{ runner.os }}-${{ hashFiles('**/*.swift') }}
        restore-keys: |
          build-${{ github.workspace }}-${{ runner.os }}-
          build-${{ github.workspace }}-
    - uses: YOCKOW/Action-setup-swift@master
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
